[package]
name = "vless"
version = "0.1.0"
edition = "2021"
default-run = "vless"

[[bin]]
name = "vless"
path = "src/main.rs"


[dependencies]
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
bytes = "1.0"
prost = "0.12"
prost-types = "0.12"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
prost-build = "0.12"
# 优化配置
[profile.release]
# 链接时优化
lto = true
# 代码生成单元数量
codegen-units = 1
# 优化级别：s=size, z=size aggressive
opt-level = "s"
# 不包含调试信息
debug = false
# 启用panic=abort减小体积
panic = "abort"